# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-11 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveycategory',
            options={'verbose_name': '问卷类别', 'verbose_name_plural': '问卷类别'},
        ),
        migrations.AlterField(
            model_name='surveyitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.SurveyCategory', verbose_name='问卷类目'),
        ),
    ]
