# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-11 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20180611_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveytitle',
            options={'verbose_name': '问卷问题', 'verbose_name_plural': '问卷问题'},
        ),
        migrations.AlterModelOptions(
            name='titlechoice',
            options={'verbose_name': '题目选项', 'verbose_name_plural': '题目选项'},
        ),
    ]
