# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-11 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20180611_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveytitle',
            name='题目提示',
        ),
        migrations.RemoveField(
            model_name='titlechoice',
            name='题目的值',
        ),
        migrations.AddField(
            model_name='surveytitle',
            name='tips',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='题目提示'),
        ),
        migrations.AddField(
            model_name='titlechoice',
            name='choice_val',
            field=models.CharField(default='', max_length=255, verbose_name='题目的值'),
        ),
    ]
