# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-11 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20180611_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveytitle',
            options={'verbose_name': '问卷题目', 'verbose_name_plural': '问卷题目'},
        ),
    ]
