# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-11 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import utils.ImageStorage


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20180611_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyitem',
            name='front_image',
            field=models.ImageField(blank=True, null=True, storage=utils.ImageStorage.ImageStorage, upload_to='survey/images/%Y/%m/%d/', verbose_name='封面图'),
        ),
    ]
