# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-11 22:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import utils.ImageStorage


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20180611_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_val', models.CharField(default='', max_length=255, verbose_name='题目的值')),
                ('nums', models.IntegerField(default=0, verbose_name='人数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='生成统计时间')),
            ],
            options={
                'verbose_name': '统计表',
                'verbose_name_plural': '统计表',
            },
        ),
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_val', models.CharField(default='', max_length=255, verbose_name='题目的值')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='ip地址')),
                ('extra_text', models.CharField(default='', max_length=200, verbose_name='是否填写其它')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '问卷答案',
                'verbose_name_plural': '问卷答案',
            },
        ),
        migrations.AlterField(
            model_name='surveyitem',
            name='front_image',
            field=models.ImageField(blank=True, null=True, storage=utils.ImageStorage.ImageStorage(), upload_to='survey/images/%Y/%m/%d/', verbose_name='封面图'),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.SurveyItem', verbose_name='问卷'),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='surveyTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.SurveyTitle', verbose_name='题目id'),
        ),
        migrations.AddField(
            model_name='answerstatic',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.SurveyItem', verbose_name='问卷'),
        ),
        migrations.AddField(
            model_name='answerstatic',
            name='surveyTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.SurveyTitle', verbose_name='题目id'),
        ),
    ]
