# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-12 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20180611_2233'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choiceanswer',
            unique_together=set([('ip', 'survey')]),
        ),
    ]
