# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-12 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20180612_2321'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choiceanswer',
            unique_together=set([('ip', 'survey', 'surveyTitle')]),
        ),
    ]
