# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-12 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_auto_20180612_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerstatic',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='answerstatic',
            name='surveyTitle',
        ),
        migrations.AddField(
            model_name='answerstatic',
            name='survey_id',
            field=models.IntegerField(default=0, verbose_name='问卷'),
        ),
        migrations.AddField(
            model_name='answerstatic',
            name='title_id',
            field=models.IntegerField(default=0, verbose_name='题目id'),
        ),
    ]
